# Kapitel 5 – Dimensionsreducering  
## Faktafrågor

---

### 1. Vad menas med curse of dimensionality?

#### Curse of dimensionality syftar på att när antalet features (dimensioner) ökar kraftigt, blir datan allt mer utspridd i rummet. Det leder till flera problem:  
    - Modeller behöver mycket mer data för att generalisera bra.  
    - Avståndsmått (t.ex. Euclidean distance) blir mindre meningsfulla.  
    - Risken för överanpassning ökar.  

#### Det är därför vanligt att använda **[dimensionsreducering](ca://s?q=Vad_%C3%A4r_dimensionsreducering)** för att minska komplexiteten.

---

### 2. Vad är dimensionsreducering och varför görs det?
#### Dimensionsreducering innebär att man minskar antalet variabler i datasetet samtidigt som man försöker behålla så mycket information som möjligt. Det görs för att:  
    - Minska risk för överfitting. 
    - Förbättra modellens prestanda.  
    - Snabba upp träning och prediktion.  
    - Göra datan mer visuellt tolkningsbar.  
    - Hantera curse of dimensionality.

#### Vanliga metoder är **PCA**, **t‑SNE**, **UMAP**.

---

### 3. Förklara översiktligt hur PCA fungerar. Använd figur 5.4 i din förklaring.
 
#### **[PCA](ca://s?q=F%C3%B6rklara_PCA)** (Principal Component Analysis) är en linjär metod som:  
    1. Identifierar riktningar i datan där variansen är som störst.  
    2. Dessa riktningar kallas **principal components**.  
    3. PCA roterar koordinatsystemet så att första komponenten fångar maximal varians, andra komponenten fångar näst mest, osv.  
    4. Man kan sedan projicera datan på de första komponenterna för att minska dimensionerna.  

#### Figur 5.4 visar hur PCA hittar en ny axel (komponent) som bäst representerar variationen i datan, och hur datan projiceras på denna axel.

---

### 4. Hur kan kernel PCA utvärderas?
 
#### Kernel PCA är en icke‑linjär variant av PCA som använder kernel‑funktioner för att fånga komplexa strukturer. Eftersom kernel PCA inte har en enkel rekonstruktion som vanlig PCA, utvärderas den genom:  
    - **[Visualisering](ca://s?q=Hur_visualiserar_man_kernel_PCA)** av de reducerade dimensionerna.
    - **Prestanda i efterföljande ML‑modell** (t.ex. klassificering eller regression).
    - **Separationsförmåga** mellan klasser i det reducerade rummet.
    - **Stabilitet** över olika kernel‑val och hyperparametrar.

#### Man bedömer alltså hur bra den reducerade representationen fungerar för det ML‑problem man vill lösa.

---

## Resonemangfrågor

---

### 5. Stina påstår att man alltid vill ha bästa möjliga prediktioner. Kalle säger att tid också är viktigt. Vad säger du?
 
#### Båda har rätt. I praktiken måste man balansera:  
    - **Prediktionskvalitet**.
    - **Träningstid**.
    - **Prediktionstid**.  
    - **Resursförbrukning**.

#### En modell som ger något bättre resultat men tar 10× längre tid kan vara opraktisk i verkligheten, särskilt i:  
    - realtidsapplikationer. 
    - stora dataset.
    - system med begränsad hårdvara.

#### Därför är det vanligt att välja en modell som är “tillräckligt bra” men snabb och stabil.

---

### 6. Efter att vi genomfört en PCA, vad händer med tolkningen av variablerna?
 
#### Efter PCA är de nya variablerna (principal components):  
    - Kombinationer av de ursprungliga variablerna.
    - Ofta svåra att tolka direkt.
    - Inte längre kopplade till en specifik fysisk eller semantisk betydelse.

#### Man förlorar alltså **tolkbarhet**, men vinner:  
    - enklare struktur.
    - mindre brus.
    - bättre separationsförmåga.
    - lägre dimensioner  

#### Det är en klassisk trade‑off mellan **tolkbarhet** och **prestanda**.

---
### 7. Gå igenom samtliga kodexempel i kapitlet och skriv gärna av koden manuellt. Det är även bra att experimentera genom att ändra vissa delar av koden och läsa dokumentationen.
---

### 8. Förklara vad nedanstående kod gör.

In [1]:
import numpy as np
from sklearn.decomposition import PCA
# Creating a dataset with 3 features/columns
X = np.random.rand(1000, 3)
print(X[0:5])
# Reducing the data to 2 dimensions
pca = PCA(n_components=2)
X2D = pca.fit_transform(X)
print(X2D[0:5])
# "Recreating" the data to 3 dimensions
X3D_inv = pca.inverse_transform(X2D)
# Not exactly equal since some information was lost in the transformation
print(np.allclose(X3D_inv, X))

[[0.45608521 0.39284802 0.72510228]
 [0.98467396 0.64163511 0.81941247]
 [0.35175569 0.09288738 0.32391848]
 [0.95130776 0.221905   0.63549616]
 [0.95256584 0.59490324 0.41902354]]
[[ 0.0184776   0.25360667]
 [ 0.5558597   0.04015058]
 [-0.41715868  0.02568896]
 [ 0.20928204 -0.00319719]
 [ 0.30920995 -0.27985879]]
False


### 9. Genomför en PCA på “car_price_dataset.csv” från kapitel 3 innan du modellerar det med ML. Hur påverkas resultatet?

#### [Här](car_price_pca.ipynb)
